---
  - hosts: all
    become: true
    tasks:
    - name: Install Tree to client
      apt:
        name: tree
        state: latest






    - name: Checking all user files for unwanted files
      ansible.builtin.shell:
        cmd: tree -f /home |grep .mp3 > file_list
    - name: Checking all user files for unwanted files
      ansible.builtin.shell:
        cmd: tree -f /home |grep .pdf >> file_list
    - name: Checking all user files for unwanted files
      ansible.builtin.shell:
        cmd: tree -f /home |grep .mov >> file_list
    - name: Checking all user files for unwanted files
      ansible.builtin.shell:
        cmd: tree -f /home |grep .pdf >> file_list
