---
- hosts: localhost
  become: true
  tasks:

  - name: Find Media Files
    include_role:
      name: find-media-files

  - name: Install Packages
    include_role:
      name: install-packages

  - name: Check Services
    include_role:
      name: check-services

  - name: Virus scan
    include_role:
      name: av-scan
    # - name: remove prexsisting logs
    #   shell:
    #     cmd: rm Logs_ansible
    #   ignore_errors: true
    #
    # - name: Checking all user files for unwanted files
    #   ansible.builtin.shell:
    #     cmd: tree -f -i /home |grep .mp3 >> Logs_ansible
    #   ignore_errors: true
    # - name: Checking all user files for unwanted files
    #   ansible.builtin.shell:
    #     cmd: tree -f -i /home |grep .pdf >> Logs_ansible
    #   ignore_errors: true
    # - name: Checking all user files for unwanted files
    #   ansible.builtin.shell:
    #     cmd: tree -f -i /home |grep .mov >> Logs_ansible
    #   ignore_errors: true
