---
  - hosts: all
    become: true
    tasks:
    - name: Install Tree to client
      apt:
        name: tree
        state: latest



    - name: find
      find:
        paths: /home/kali/*
        patterns: '*.png'
      register: files_matched

    - debug:
        #msg: "{{ files_matched.files[0].path }}"
        msg: "{{ files_matched }}"

    - name: Checking all user files for unwanted files
      ansible.builtin.shell:
        cmd: ls -R /home/* |grep *.png >> output
      register: Unwantedfile

    - debug:
        #msg: "{{ files_matched.files[0].path }}"
        msg: "{{ Unwantedfile }}"
