---
  - hosts: all
    become: true
    tasks:
  - name: Find /var/log files equal or greater than 10 megabytes ending with .old or .log.gz
    find:
    paths: /home/kali/Downloads
    patterns: '*.jpeg'
