---
- name: Install Tree
  apt:
    name:
      - tree

- name: remove prexsisting logs
  shell:
    cmd: rm Logs_ansible
  ignore_errors: true

- name: Checking all user files for unwanted files
  ansible.builtin.shell:
    cmd: tree -f -i /home |grep .mp3 >> Logs_ansible
  ignore_errors: true

- name: Checking all user files for unwanted files
  ansible.builtin.shell:
    cmd: tree -f -i /home |grep .mp4 >> Logs_ansible
  ignore_errors: true

- name: Checking all user files for unwanted files
  ansible.builtin.shell:
    cmd: tree -f -i /home |grep .mov >> Logs_ansible
  ignore_errors: true

- name: Checking all user files for unwanted files
  ansible.builtin.shell:
    cmd: tree -f -i /home |grep .txt >> Logs_ansible
  ignore_errors: true

- name: Checking all user files for unwanted files
  ansible.builtin.shell:
    cmd: tree -f -i /home |grep .pdf >> Logs_ansible
  ignore_errors: true
